include:
  - ./compose/docmost.yml
  - ./compose/infrastructure.yml
  - ./compose/cashly.yml
  - ./compose/nextcloud.yml
  - ./compose/portfolio.yml
  - ./compose/fortil-excel-timesheet.yml
  - ./compose/mr-white.yml
  - ./compose/lafa-tools.yml
  - ./compose/appflowy.yml

# --- NETWORKS ---
# Rete comune utilizzata per la comunicazione tra tutti i servizi
networks:
  common-network:
    driver: bridge
    name: common-network

# --- VOLUMES ---
# Definizione dei volumi condivisi/esterni
volumes:
  postgres_data:
    external: true
    name: cashly-db_postgres_data
  nextcloud_db_data:
    external: true
    name: nextcloud-db_data
  nextcloud_data:
    external: true
    name: nextcloud_app_data
