server {
    listen 80;

    root /var/www;

    location = /robots.txt {
        try_files /seos/$host/robots.txt /seos/default/robots.txt =404;
        allow all;
        log_not_found off;
        access_log off;
    }

    location = /sitemap.xml {
        try_files /seos/$host/sitemap.xml =404;
        allow all;
        log_not_found off;
        access_log off;
    }

    location /seos/ {
        internal;
    }

    location / {
        return 301 $scheme://$host/calcolatore-tasse/;
    }

    location = /calcolatore-finanze {
        return 301 $scheme://$host$request_uri/;
    }

    location /calcolatore-finanze/ {
        index index.html;
        try_files $uri $uri/ /calcolatore-finanze/index.html;
    }

    location = /calcolatore-tasse {
        return 301 $scheme://$host$request_uri/;
    }

    location /calcolatore-tasse/ {
        index index.html;
        try_files $uri $uri/ /calcolatore-tasse/index.html;
    }
}
